name: Deploy Website
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Setup Cargo
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Install Build Dependencies
        run: cargo install trunk bonnie

      - name: Build Website
        run: trunk build --release

      - name: Deploy to GitHub Pages
        run: |
          git worktree add gh-pages gh-pages
          git config user.name "deploy-rs"
          git config user.email "deploy@azumi.is-an.app"
          cd gh-pages

          # Delete the ref to avoid keeping history.
          git update-ref -d refs/heads/gh-pages
          rm -rf *
          mv ../dist/* .
          git add .
          git commit -m "Redeploy Website"
          git push --force
