name: Deploy Website
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 17
      
      - name: Setup Tailwind
        run: npm i -g tailwindcss

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          default: true

      - name: Install Build Dependencies
        run: cargo install trunk bonnie

      - name: Build Website
        run: trunk build --release

      - name: Deploy Website
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          clean: true
          force: true
